In [2]:
import torch

In [3]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [4]:
a[1]

tensor(1.)

In [5]:
float(a[1])

1.0

In [6]:
a[2]

tensor(1.)

In [7]:
points = torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [8]:
points = torch.tensor([1,3,4,4,3,2])
points

tensor([1, 3, 4, 4, 3, 2])

In [9]:
float(points[0]) , float(points[1])

(1.0, 3.0)

In [10]:
tensor_2d = torch.tensor([[2,3], [4,5],[7,6]])
tensor_2d

tensor([[2, 3],
        [4, 5],
        [7, 6]])

In [11]:
tensor_2d.shape

torch.Size([3, 2])

In [12]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [13]:
points = torch.tensor([[2,3], [4,5], [7,3]])
points

tensor([[2, 3],
        [4, 5],
        [7, 3]])

In [14]:
points[0,1]

tensor(3)

In [15]:
points[1,1]

tensor(5)

In [16]:
points[0]

tensor([2, 3])

In [17]:
points[1:]

tensor([[4, 5],
        [7, 3]])

In [18]:
points[1:, :]

tensor([[4, 5],
        [7, 3]])

In [19]:
points[1: , 0]

tensor([4, 7])

In [20]:
points[1: , 1]

tensor([5, 3])

In [21]:
points[None]

tensor([[[2, 3],
         [4, 5],
         [7, 3]]])

In [22]:
img_t = torch.randn(3,5,5)
img_t

tensor([[[ 1.5770,  0.2144, -0.1034,  1.0660,  0.2551],
         [-0.4259, -0.0130,  0.1751,  0.7726,  1.9117],
         [-0.4279, -1.0504, -0.6043, -1.3009, -0.2144],
         [ 1.1337,  2.2782,  1.3783, -0.9829,  1.2821],
         [-1.2475,  0.2122, -0.5776,  0.4935,  2.2963]],

        [[ 0.1217, -0.5454, -0.4740, -0.6306,  1.2403],
         [-2.2821,  0.2225, -0.8578, -0.0256,  2.1118],
         [-1.9849,  0.9874,  0.2155,  0.1986, -0.5634],
         [-0.5580,  0.4157,  0.6086,  0.1200,  0.8979],
         [ 1.1403, -0.0502,  0.0623, -0.5111, -1.5550]],

        [[ 1.1318,  0.2484, -1.8869,  0.5862,  0.2816],
         [ 0.5364, -1.1625, -2.0262,  1.6716,  1.3065],
         [-2.1473, -0.1572,  0.8768, -2.3914,  0.8484],
         [-0.5210, -0.6892, -0.0396,  1.7399, -0.3504],
         [ 1.2790, -0.4654,  0.5781,  0.7523,  2.3528]]])

In [23]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [24]:
batch_t = torch.randn(2,3,5,5)
batch_t

tensor([[[[-0.4832,  1.1163,  0.2297,  1.3053,  0.8597],
          [-0.7357,  0.0963,  0.6803, -1.5604, -1.8804],
          [-1.2830, -0.2902,  1.4040,  0.1300,  0.5758],
          [-1.2062, -1.2934, -0.6244, -0.3347,  0.2496],
          [-1.0569,  0.0615, -1.9105, -1.0198,  0.2773]],

         [[-2.4060,  1.4400,  1.7070, -0.9829, -1.5382],
          [ 0.3531,  3.0506, -1.3698,  1.0430, -0.2709],
          [ 1.1437, -1.2649, -1.0059, -0.6507, -1.4943],
          [-0.5050, -0.3468,  0.2494,  0.5199, -0.6219],
          [ 0.0066, -0.5342, -1.4485, -0.3885, -0.6909]],

         [[ 0.6620, -0.3454,  1.6391, -0.6625, -0.3181],
          [-0.3430,  0.4152,  1.1628, -0.0765,  1.5958],
          [-0.9646,  0.2829,  0.5869, -1.5576, -0.0137],
          [ 1.6474, -0.2474, -2.0106, -2.2407, -0.1879],
          [ 2.4349, -0.6462,  0.9696,  0.4233, -1.7476]]],


        [[[ 1.4518, -0.5959, -0.3511,  1.3652,  0.0121],
          [-0.7789,  2.0022, -0.0657,  1.2290,  0.8207],
          [ 2.0383, -0.

In [25]:
img_t_graynaive = img_t.mean(-3)
batch_t_naive = batch_t.mean(-3)
img_t_graynaive.shape , batch_t_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [26]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_weighted = img_weights.sum(-3)
batch_weighted = batch_weights.sum(-3)
img_weighted.shape , batch_weighted.shape , unsqueezed_weights.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]), torch.Size([3, 1, 1]))

In [27]:
double_points = torch.ones(2 , 10 , dtype = torch.double)
double_points

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=torch.float64)

In [28]:
short_points = torch.tensor([[1 , 2], [2, 3]], dtype = torch.short)
short_points

tensor([[1, 2],
        [2, 3]], dtype=torch.int16)

In [29]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [30]:
points = torch.tensor([[2,3], [4,2], [8,6]])
points.storage()

C:\Users\Admin\AppData\Local\Temp\ipykernel_27740\263274809.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 2
 3
 4
 2
 8
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [31]:
a = torch.ones(3,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [32]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [33]:
points = torch.tensor([[2,3], [4,2], [8,6]])
second_point = points[1]
second_point.storage_offset()

2

In [34]:
points.stride()

(2, 1)

In [42]:
second_point = points[1].clone()
second_point[0]=10.0
second_point, points, second_point.size() , second_point.storage_offset(), second_point.stride()

(tensor([10,  2]),
 tensor([[2, 3],
         [4, 2],
         [8, 6]]),
 torch.Size([2]),
 0,
 (1,))

In [45]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [47]:
some_t = torch.ones(3,4,5)
trans= some_t.transpose(0,2)
some_t.shape , trans.shape

(torch.Size([3, 4, 5]), torch.Size([5, 4, 3]))

In [49]:
num = some_t.numpy()
num

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)

In [51]:
points = torch.from_numpy(num)
points

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [57]:
a = torch.tensor(list(range(9)))
a , a.shape, a.stride(), a.storage_offset()

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([9]), (1,), 0)

In [60]:
b = a.view(3, 3)
b , a.storage(), b.storage()

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
  0
  1
  2
  3
  4
  5
  6
  7
  8
 [torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9],
  0
  1
  2
  3
  4
  5
  6
  7
  8
 [torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9])

In [63]:
c =b[1:, 1:]
c , c.shape, c.stride(), c.storage_offset()

(tensor([[4, 5],
         [7, 8]]),
 torch.Size([2, 2]),
 (3, 1),
 4)

In [64]:
torch.cos(a)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])