In [1]:
import torch

In [2]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[1]

tensor(1.)

In [4]:
float(a[1])

1.0

In [5]:
a[2]

tensor(1.)

In [6]:
points = torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [7]:
points = torch.tensor([1,3,4,4,3,2])
points

tensor([1, 3, 4, 4, 3, 2])

In [8]:
float(points[0]) , float(points[1])

(1.0, 3.0)

In [9]:
tensor_2d = torch.tensor([[2,3], [4,5],[7,6]])
tensor_2d

tensor([[2, 3],
        [4, 5],
        [7, 6]])

In [10]:
tensor_2d.shape

torch.Size([3, 2])

In [11]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [12]:
points = torch.tensor([[2,3], [4,5], [7,3]])
points

tensor([[2, 3],
        [4, 5],
        [7, 3]])

In [13]:
points[0,1]

tensor(3)

In [14]:
points[1,1]

tensor(5)

In [15]:
points[0]

tensor([2, 3])

In [16]:
points[1:]

tensor([[4, 5],
        [7, 3]])

In [17]:
points[1:, :]

tensor([[4, 5],
        [7, 3]])

In [18]:
points[1: , 0]

tensor([4, 7])

In [19]:
points[1: , 1]

tensor([5, 3])

In [20]:
points[None]

tensor([[[2, 3],
         [4, 5],
         [7, 3]]])

In [21]:
img_t = torch.randn(3,5,5)
img_t

tensor([[[ 0.4884,  1.0650, -1.2144, -1.9058, -0.4671],
         [-0.1856, -1.5679,  3.0846, -0.0975, -2.0330],
         [-0.2448,  0.3289, -0.9162,  1.2049, -0.7179],
         [ 0.3206, -0.8991, -0.8416, -0.7100,  0.6557],
         [ 1.5315, -1.5888, -0.4999, -0.3810, -0.2317]],

        [[ 0.2475,  0.6477, -2.2928, -0.7413, -1.6996],
         [ 1.5089,  0.2605, -2.3944,  1.1526,  1.1132],
         [-1.6137, -1.7675,  0.8577,  0.0664, -0.7833],
         [-1.4707,  1.9328,  0.5011, -0.5432,  0.4535],
         [ 1.2849, -0.6119, -0.0501,  1.1779,  0.7932]],

        [[-1.3156,  0.8998, -0.8745,  0.6162, -0.1343],
         [ 1.2004, -1.4600,  0.3578,  0.1076, -0.4226],
         [ 0.0473,  1.5328, -2.4135, -0.3157,  0.7822],
         [-1.3175,  1.3971,  0.7164,  0.0532,  0.8881],
         [-1.8496, -1.4008,  1.9378, -1.4215, -0.6774]]])

In [22]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [23]:
batch_t = torch.randn(2,3,5,5)
batch_t

tensor([[[[ 1.4331e+00,  7.4375e-01,  3.9653e-01,  3.4477e-01, -1.4470e+00],
          [-5.3165e-01, -2.7642e-01,  4.1452e-01,  8.1740e-02,  2.5104e-01],
          [ 1.1642e+00, -9.8949e-01, -5.0676e-01,  1.0097e+00,  2.0122e+00],
          [ 3.0822e-01, -1.0255e+00,  1.7035e+00, -1.6646e+00, -1.4194e-01],
          [ 4.6014e-01,  1.0336e+00,  2.9938e-02,  4.3974e-01, -1.1474e+00]],

         [[-5.7301e-02,  1.5893e+00, -2.8151e-01,  3.2416e-01, -6.9240e-01],
          [ 2.3407e+00,  2.3936e-01, -4.2749e-02, -2.6903e-02, -6.8283e-01],
          [-3.4369e-01,  1.4964e+00,  8.2484e-02,  1.1145e-01, -4.2243e-02],
          [ 3.2870e-01,  1.7805e+00,  7.4210e-02, -1.9423e+00,  4.3611e-01],
          [-8.3885e-01, -3.1509e-01,  1.1345e+00, -5.0220e-01,  4.0889e-01]],

         [[-9.6924e-01, -1.1492e-03,  2.2213e-01, -6.3667e-01,  1.3241e+00],
          [-1.4662e+00,  2.1482e+00, -3.7891e-02, -1.9227e+00, -2.4718e+00],
          [ 8.9773e-01, -3.5627e-01,  2.1287e+00,  1.0108e+00, -7.1022e-

In [24]:
img_t_graynaive = img_t.mean(-3)
batch_t_naive = batch_t.mean(-3)
img_t_graynaive.shape , batch_t_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [25]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_weighted = img_weights.sum(-3)
batch_weighted = batch_weights.sum(-3)
img_weighted.shape , batch_weighted.shape , unsqueezed_weights.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]), torch.Size([3, 1, 1]))

In [26]:
double_points = torch.ones(2 , 10 , dtype = torch.double)
double_points

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=torch.float64)

In [27]:
short_points = torch.tensor([[1 , 2], [2, 3]], dtype = torch.short)
short_points

tensor([[1, 2],
        [2, 3]], dtype=torch.int16)

In [28]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [29]:
points = torch.tensor([[2,3], [4,2], [8,6]])
points.storage()

C:\Users\Admin\AppData\Local\Temp\ipykernel_53576\263274809.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 2
 3
 4
 2
 8
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [30]:
a = torch.ones(3,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [31]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [32]:
points = torch.tensor([[2,3], [4,2], [8,6]])
second_point = points[1]
second_point.storage_offset()

2

In [33]:
points.stride()

(2, 1)

In [34]:
second_point = points[1].clone()
second_point[0]=10.0
second_point, points, second_point.size() , second_point.storage_offset(), second_point.stride()

(tensor([10,  2]),
 tensor([[2, 3],
         [4, 2],
         [8, 6]]),
 torch.Size([2]),
 0,
 (1,))

In [35]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [36]:
some_t = torch.ones(3,4,5)
trans= some_t.transpose(0,2)
some_t.shape , trans.shape

(torch.Size([3, 4, 5]), torch.Size([5, 4, 3]))

In [37]:
num = some_t.numpy()
num

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)

In [38]:
points = torch.from_numpy(num)
points

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [39]:
a = torch.tensor(list(range(9)))
a , a.shape, a.stride(), a.storage_offset()

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([9]), (1,), 0)

In [40]:
b = a.view(3, 3)
b , a.storage(), b.storage()

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
  0
  1
  2
  3
  4
  5
  6
  7
  8
 [torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9],
  0
  1
  2
  3
  4
  5
  6
  7
  8
 [torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9])

In [41]:
c =b[1:, 1:]
c , c.shape, c.stride(), c.storage_offset()

(tensor([[4, 5],
         [7, 8]]),
 torch.Size([2, 2]),
 (3, 1),
 4)

In [42]:
torch.cos(a)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [43]:
a = torch.ones(128, 8)
a, a.shape

(tensor([[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]),
 torch.Size([128, 8]))

In [44]:
torch.sum(a, dim=0, keepdim=True)

tensor([[128., 128., 128., 128., 128., 128., 128., 128.]])

In [45]:
a.sum(dim=1, keepdim=True).shape

torch.Size([128, 1])